apiVersion: apps/v1
kind: Deployment
metadata:
  name: ews-api
  namespace: patient-ews
  labels:
    app: ews-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ews-api
  template:
    metadata:
      labels:
        app: ews-api
    spec:
      containers:
      - name: ews-api
        image: patient-ews:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ews-secrets
              key: database-url
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: QDRANT_HOST
          value: "qdrant-service"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: ews-secrets
              key: api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: log-storage
          mountPath: /app/logs
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
      - name: log-storage
        persistentVolumeClaim:
          claimName: log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ews-api-service
  namespace: patient-ews
spec:
  selector:
    app: ews-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: patient-ews
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: patient-ews
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: ews-secrets
  namespace: patient-ews
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2V3c191c2VyOnNlY3VyZV9wYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvcGF0aWVudF9ld3M=  # postgresql://ews_user:secure_password@postgres-service:5432/patient_ews
  api-key: c2VjdXJlLWFwaS1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # secure-api-key-change-in-production